/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author indy256
 */

#include <bits/stdc++.h>

using namespace std;

constexpr long long LEN = 10'000'000'000;

bool win(const vector<pair<long long, long long>> a) {
    int g = 0;
    for (auto x: a) {
        long long l = x.second - x.first + 1;
        if (l >= LEN && l < 2 * LEN) {
            g ^= 1;
        } else if (l >= 2 * LEN && l <= 3 * LEN - 2) {
            g ^= 2;
        } else {
            return false;
        }
    }
    return g == 0;
}

void solve(istream &in, ostream &out) {
    int T, W;
    in >> T >> W;

//    vector<int> g(1001);
//    for (int i = 0; i < g.size(); ++i) {
//        set<int> s;
//        for (int j = 0; j + 100 <= i; ++j) {
//            int cur = g[j] ^g[i - j - 100];
//            s.insert(cur);
//        }
//        int mex = 0;
//        for (int j = 0;; ++j) {
//            if (!s.count(j)) {
//                mex = j;
//                break;
//            }
//        }
//        g[i] = mex;
//        cout << "g[" << i << "] = " << g[i] << endl;
//    }

    for (int t = 0; t < T; ++t) {
        vector<pair<long long, long long>> a;
        a.emplace_back(1, 1000'000'000'000);
        while (true) {
            long long P;
            in >> P;
            if (P == -2 || P == -3)break;
            auto it = lower_bound(a.begin(), a.end(), make_pair(P, 0LL));
            pair<long long, long long> p1 = {it->first, P - 1};
            pair<long long, long long> p2 = {P + LEN, it->second};
            int pos = it - a.begin();
            a.erase(a.begin() + pos);
            if (p2.first < p2.second)a.insert(a.begin() + pos, p2);
            if (p1.first < p1.second)a.insert(a.begin() + pos, p1);

            long long any = -1;
            bool found = false;
            for (int i = 0; i < a.size(); i++) {
                auto x = a[i];
                if (x.second - x.first + 1 >= LEN) {
                    vector<pair<long long, long long>> b = a;
                    long long P = x.first;
                    pair<long long, long long> p1 = {x.first, P - 1};
                    pair<long long, long long> p2 = {P + LEN, it->second};
                    b.erase(b.begin() + i);
                    if (p2.first < p2.second)b.push_back(p2);
                    if (p1.first < p1.second)b.push_back(p1);
                    any = P;
                    if (win(b)) {
                        out << P << endl;
                        out.flush();
                        found = true;
                        break;
                    }
                }
                if (x.second - x.first + 1 >= LEN) {
                    vector<pair<long long, long long>> b = a;
                    long long P = x.first + (x.second - x.first + 1 - LEN) / 2;
                    pair<long long, long long> p1 = {x.first, P - 1};
                    pair<long long, long long> p2 = {P + LEN, it->second};
                    b.erase(b.begin() + i);
                    if (p2.first < p2.second)b.push_back(p2);
                    if (p1.first < p1.second)b.push_back(p1);
                    any = P;
                    if (win(b)) {
                        out << P << endl;
                        out.flush();
                        found = true;
                        break;
                    }
                }
            }
            if (!found) {
                out << any << endl;
                out.flush();
            }
        }
    }

    int res = 0;
    out << res << endl;
}


int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solve(in, out);
}
